name: Java CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Vérifie le dépôt
      - name: Checkout code
        uses: actions/checkout@v3

      # Configure Java
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'  # Distribution Java (open-source)
          java-version: '21'       # Version de Java à utiliser

      # Construire le projet
      - name: Build with Maven
        run: mvn clean install

      # Exécuter les tests
      - name: Run Tests
        run: mvn test
